### ISSUE TITLE
Create "algorithm-main-section" components

### ISSUE THREAD

**Issue by MackoLee** [Big-Dipper-Code/Big-Dipper#14]
### 알고리즘 문제를 풀기위한 구간의 화면 설계에 따른 컴포넌트 생성
<img width="371" alt="image" src="https://user-images.githubusercontent.com/11310445/203572528-94966484-03bb-45c4-9281-8e7fe356519a.png">

본인이 만드려고 정해진 view나 component는 **댓글**로 작업을 한다고 하고 **브런치를 만들어서 작업**해주시기 바랍니다.

View 레이아웃 클래스 구조는 
*-section, *-wrap, *-content 순으로 한다. 

파일구조 다른 제안사항이 있으면 얘기해주세요.
```
views
ᄂ AlgorithmView
    ᄂ index.vue
    ᄂ QuestionView
        ᄂ index.vue
    ᄂ InputView
        ᄂ index.vue
    ᄂ OutputView
        ᄂ index.vue
    ᄂ CodeBlocksView
        ᄂ index.vue
```

간단한 블록이라도 UI통일성을 위해서 컴포넌트로 제작
```
components
ᄂ CodeBlock.vue
ᄂ CodeBlockAddButton.vue
```

**Comment by MackoLee** [comment]
CodeBlock에 대한 아이디어 [다이나믹 컴포넌트](https://vuejs.org/guide/essentials/component-basics.html#dynamic-components)를 활용해서 Block의 역할마다 다른 컴포넌트를 제작하고 기능이나 메소드가 겹칠경우 mixin을 활용하면 어떨까요?

**Comment by MackoLee** [comment]
CodeBlock의 객체구조를 정해야함
```json
[ {
    "b_id": 0,
    "name":"",
    "function":"if", //while,  for, input, output, endif
    "category": "basic",
    "params":["1==1"],
    "color": "",
    "shape": "square",
},
{
 
}] 순서 보장
```

**Comment by Harmon96** [comment]
- 각 블록들에 대한 공통기능들 ex) 블록의 변수, 색, 모양등은 mixin으로 활용하면 좋을것 같습니다.
