### ISSUE TITLE
시작관련 문서 Notion 등

### ISSUE THREAD

**Issue by MackoLee** [Big-Dipper-Code/Big-Dipper#4]
## Summary
- [x] Notion 연결, 간트차트 작성
- [x] 2022.11.14 회의록

**Comment by Harmon96** [comment]
## Summary
- [Notion 링크, 간트차트, 회의록](https://www.notion.so/0490fb5a21464d8b80b6a70c009afcf3?v=7a5db95fab394fd39214ae435c491430)

**Comment by MackoLee** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/11310445/202194984-c3945fef-b944-43f4-a350-c449396c20a5.png">

notion이 안들어가지던데 권한을 받아야할거 같네요
그리고 notion수정은 안돼도 모든 사람이 볼수있게는 해주면 좋을 것 같아요!

**Comment by Harmon96** [comment]
## Summary
- 모든 사람들에게 웹으로 공유 가능하도록 하였습니다.
- 위 이메일 (s201833141@ajou.ac.kr)에 notion 초대메일을 보냈습니다.

## Description
- [웹 공유 링크](https://separate-shamrock-789.notion.site/0490fb5a21464d8b80b6a70c009afcf3?v=7a5db95fab394fd39214ae435c491430)
